GridExampleMVC/Controllers/ReporteController.cs
using GridExampleMVC.Models;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Web.UI.WebControls;
using System.IO;
using System.Web.UI;
using System.Collections;
using ClosedXML.Excel;
using System.Data;

namespace GridExampleMVC.Controllers
{
    public class ReporteController : Controller
    {

        private DB_DCMEntities db = new DB_DCMEntities();


        // GET: Asset
        public ActionResult Defectos()
        {
            DateTime date1 = DateTime.Now.AddDays(-7);
            DateTime date2 = DateTime.Now;
            string sord = "%";
            return View(db.DCM_ReportGeneral(sord, date1,date2));
        }

        // GET: Asset
        public ActionResult Productividad()
        {
            DateTime date1 = DateTime.Now.AddDays(-7);
            DateTime date2 = DateTime.Now;
            return View(db.DCM_ReportProductivity("%","%","%","%","%",date1,date2));
        }


        // GET: Asset
        public ActionResult ProdTiempoReal()
        {
            DateTime date1 = DateTime.Now;
            return View(db.DCM_ReportLineProdBETA(7,1,date1));
        }

        [HttpPost]
        public ActionResult Defectos(string sord, string finicial, string ffinal)
        {
            if (string.IsNullOrEmpty(sord))
            {
                sord = "%";
            }
            if (string.IsNullOrEmpty(finicial))
            {
                DateTime date1 = DateTime.Now.AddDays(-7);
                finicial = date1.ToString();
            }

            if (string.IsNullOrEmpty(ffinal))
            {
                DateTime date2 = DateTime.Now;
                ffinal = date2.ToString();
            }

            return View(db.DCM_ReportGeneral(sord, DateTime.Parse(finicial), DateTime.Parse(ffinal)));
        }

        [HttpPost]
        public ActionResult Productividad(string finicial, string ffinal)
        {
            if (string.IsNullOrEmpty(finicial))
            {
                DateTime date1 = DateTime.Now.AddDays(-7);
                finicial = date1.ToString();
            }

            if (string.IsNullOrEmpty(ffinal))
            {
                DateTime date2 = DateTime.Now;
                ffinal = date2.ToString();
            }

            return View(db.DCM_ReportProductivity("%", "%", "%", "%", "%", DateTime.Parse(finicial), DateTime.Parse(ffinal)));
        }



    }
}

GridExampleMVC/Views/Reporte/Defectos.cshtml
@model IEnumerable<GridExampleMVC.Models.DCM_ReportGeneral_Result>

@{
    ViewBag.Title = "Defectos";
}

<div class="row">
    <div class="col-md-12">
        <div id="list-panel">
            <div class="panel-body">
                <!--<div class="dt-button-collection">
                    <input type="button" id="btnExport" value="Excel" />
                    <a class="btn btn-primary btn-sm" tabindex="0" aria-controls="assets-data-table"><span>PDF</span></a>
                    <a class="btn btn-primary btn-sm" tabindex="0" aria-controls="assets-data-table"><span>Imprimir</span></a><br/> <br/>  
                </div>-->
                @using (Html.BeginForm("Defectos", "Reporte", FormMethod.Post))
                {

                    
                    @Html.Partial("_Searchby")

                    <div id="dvData">
                        <table id="assets-data-table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.EnterRegis)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.User)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Cliente)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Folio)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Fecha)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Turno)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Divicion)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Equipo)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Celda)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.SO_)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.SO__Cant)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Item)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Item_Descrip)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Categoria)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Responsable)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Cod_Def)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.FamDefecto)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Descripcion_de_Defecto)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Cant_Def)</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.EnterRegis)</td>
                                        <td>@Html.DisplayFor(modelItem => item.User)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Cliente)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Folio)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Turno)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Divicion)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Equipo)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Celda)</td>
                                        <td>@Html.DisplayFor(modelItem => item.SO_)</td>
                                        <td>@Html.DisplayFor(modelItem => item.SO__Cant)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Item)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Item_Descrip)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Categoria)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Responsable)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Cod_Def)</td>
                                        <td>@Html.DisplayFor(modelItem => item.FamDefecto)</td>
                                        <td>@Html.DisplayFor(model => item.Descripcion_de_Defecto)</td>
                                        <td>@Html.DisplayFor(model => item.Cant_Def)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                        <div id="menu2" class="tab-pane fade">
                            
                            <p>Some content in menu 2.</p>
                        </div>

                        }
                    </div>
        </div>
    </div>
</div>

@section Scripts
{

<!--Data Tables jQuery-->
    
 <script type="text/javascript">
     $(document).ready(function () {
         $('#assets-data-table').DataTable({
             paging: false,
             info: false,
             "language": {
                 "lengthMenu": "Mostrando _MENU_ registros por página",
                 "zeroRecords": "No se encontro nada con ese criterio",
                 "infoEmpty": "No hay información disponible",
                 "search": "Buscar en esta lista",
             }

         });
         $('#exportexcel').bind('click', function (e) {
             $('#assets-data-table').tableExport({ type: 'excel', escape: 'false' });
         });
         $('#datetimepicker1').datetimepicker();
     });

</script>   
    
 }

GridExampleMVC/Views/Reporte/Index.cshtml
@model IEnumerable<GridExampleMVC.Models.DCM_ReportGeneral_Result>

@{
    ViewBag.Title = "Index - PRUEBA";
}

<div class="row">
    <div class="col-md-12">
        <div id="list-panel">
            <div class="panel-body">
                <!--<div class="dt-button-collection">
                    <input type="button" id="btnExport" value="Excel" />
                    <a class="btn btn-primary btn-sm" tabindex="0" aria-controls="assets-data-table"><span>PDF</span></a>
                    <a class="btn btn-primary btn-sm" tabindex="0" aria-controls="assets-data-table"><span>Imprimir</span></a><br/> <br/>
                </div>-->
                @using (Html.BeginForm("Index", "Reporte", FormMethod.Post))
                {
                <span>
                    Shop Order: 
                </span>
                    @Html.TextBox("sord")
                    <input type="submit" value="Generar" />
                <div id="dvData">
                    <table id="assets-data-table" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th class="column-title">@Html.DisplayNameFor(model => model.EnterRegis)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.User)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Cliente)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Folio)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Fecha)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Turno)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Divicion)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Equipo)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Celda)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.SO_)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.SO__Cant)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Item)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Item_Descrip)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Categoria)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Responsable)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Cod_Def)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.FamDefecto)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Descripcion_de_Defecto)</th>
                                <th class="column-title">@Html.DisplayNameFor(model => model.Cant_Def)</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.EnterRegis)</td>
                                    <td>@Html.DisplayFor(modelItem => item.User)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Cliente)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Folio)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Turno)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Divicion)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Equipo)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Celda)</td>
                                    <td>@Html.DisplayFor(modelItem => item.SO_)</td>
                                    <td>@Html.DisplayFor(modelItem => item.SO__Cant)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Item)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Item_Descrip)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Categoria)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Responsable)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Cod_Def)</td>
                                    <td>@Html.DisplayFor(modelItem => item.FamDefecto)</td>
                                    <td>@Html.DisplayFor(model => item.Descripcion_de_Defecto)</td>
                                    <td>@Html.DisplayFor(model => item.Cant_Def)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts
{

    <!--Data Tables jQuery-->

    <script type="text/javascript">
     $(document).ready(function () {
         $("#btnExport").click(function (e) {
             window.open('data:application/vnd.ms-excel,' + $('#dvData').html());
             e.preventDefault();
         });

         $('#assets-data-table').DataTable({
             "searching": false,
             "language": {
                 "lengthMenu": "Mostrando _MENU_ registros por página",
                 "zeroRecords": "No se encontro nada con ese criterio",
                 "info": "Mostrando _PAGE_ de _PAGES_",
                 "infoEmpty": "No hay información disponible",
                 "search": "Buscar",
                 "paginate": {
                     "next": "Siguiente",
                     "previous": "Anterior"
                 },
                 "infoFiltered": "(filtrado de _MAX_ registros)"
             }
         });
     });

    </script>

}

GridExampleMVC/Views/Reporte/ProdTiempoReal.cshtml
@model IEnumerable<GridExampleMVC.Models.DCM_ReportLineProdBETA_Result>

@{
    ViewBag.Title = "Producción en Tiempo Real (Carga 5 minutos)";
}

<div class="row">
    <div class="col-md-12">
        <div id="list-panel">
            <div class="panel-body">

                    <div class="col-md-q">
                        <br />
                        <span class="input-group-btn" style="padding-top: 5px" ;">
                            <input type="button" value="Exportar" class="btn btn-success" id="exportexcel">
                        </span>
                    </div>

                    <div id="dvData">
                        <table id="assets-data-table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th class="column-title"></th>
                                    <th class="column-title"></th>
                                    <th class="column-title" colspan="2" style="text-align: center;">S.O. Próximo</th>
                                    <th class="column-title"></th>
                                    <th class="column-title" colspan="2" style="text-align: center;">S.O. Actual</th>
                                    <th class="column-title" colspan="3" style="text-align: center;">Productividad Actual</th>
                                    <th class="column-title"></th>
                                    <th class="column-title" colspan="2" style="text-align: center;">Eventos</th>
                                    <th class="column-title" colspan="3" style="text-align: center;">Balance de S.O. Actual</th>
                                    <th class="column-title"></th>
                                </tr>
                                <tr>
                                    <th class="column-title" title="Linea activa que esta trabajando el S.O">@Html.DisplayNameFor(model => model.LINE)</th>
                                    <th class="column-title" title="Area/Cliente">@Html.DisplayNameFor(model => model.AREA)</th>
                                    <th class="column-title" title="Número de Shop Order">@Html.DisplayNameFor(model => model.N_SO_)</th>
                                    <th class="column-title" title="Número de Item">@Html.DisplayNameFor(model => model.N_ITEM)</th>
                                    <th class="column-title" style="width: 92px;">@Html.DisplayNameFor(model => model.TR_N_SO)</th>
                                    <th class="column-title" title="Número de shop order actualmente corriendo" >@Html.DisplayNameFor(model => model.A_SO_)</th>
                                    <th class="column-title" title="Item actualmente corriendo">@Html.DisplayNameFor(model => model.A_ITEM)</th>
                                    <th class="column-title" title="Producción Standard">@Html.DisplayNameFor(model => model.PRODSTD)</th>
                                    <th class="column-title" title="Producción Actual">@Html.DisplayNameFor(model => model.PRODACT)</th>
                                    <th class="column-title" title="Porcentaje de la producción standard">@Html.DisplayNameFor(model => model.PERCENTAGE)</th>
                                    <th class="column-title" title="Cantidad producida actual">@Html.DisplayNameFor(model => model.A_QTY)</th>
                                    <th class="column-title" title="Total de defectos">@Html.DisplayNameFor(model => model.DEFQTY)</th>
                                    <th class="column-title" title="Tiempo muerto acumulado (en minutos)">@Html.DisplayNameFor(model => model.TMMIN)</th>
                                    <th class="column-title" title="Cantidad ideal del S.O.">@Html.DisplayNameFor(model => model.SO_QTY)</th>
                                    <th class="column-title" title="Cantidad total actual">@Html.DisplayNameFor(model => model.GENERAL)</th>
                                    <th class="column-title" title="Diferencia entre cantidad ideal y actual">@Html.DisplayNameFor(model => model.DIFF)</th>
                                    <th class="column-title" title="Estatus de la linea">@Html.DisplayNameFor(model => model.INACTIVE)</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.LINE)</td>
                                        <td>@Html.DisplayFor(modelItem => item.AREA)</td>
                                        <td>@Html.DisplayFor(modelItem => item.N_SO_)</td>
                                        <td>@Html.DisplayFor(modelItem => item.N_ITEM)</td>
                                        <td>@Html.DisplayFor(modelItem => item.TR_N_SO)</td>
                                        <td>@Html.DisplayFor(modelItem => item.A_SO_)</td>
                                        <td>@Html.DisplayFor(modelItem => item.A_ITEM)</td>
                                        <td>@Html.DisplayFor(modelItem => item.PRODSTD)</td>
                                        <td>@Html.DisplayFor(modelItem => item.PRODACT)</td>
                                        <td>@Html.DisplayFor(modelItem => item.PERCENTAGE)</td>
                                        <td>@Html.DisplayFor(modelItem => item.A_QTY)</td>
                                        <td>@Html.DisplayFor(modelItem => item.DEFQTY)</td>
                                        <td>@Html.DisplayFor(modelItem => item.TMMIN)</td>
                                        <td>@Html.DisplayFor(modelItem => item.SO_QTY)</td>
                                        <td>@Html.DisplayFor(modelItem => item.GENERAL)</td>
                                        <td>@Html.DisplayFor(modelItem => item.DIFF)</td>
                                        <td>
                                            <div class="led-box">
                                                @if (item.INACTIVE == 1)
                                                {
                                                    <div class="led-red">
                                                    </div>
                                                }
                                                else
                                                {
                                                    <div class="led-green"></div>
                                                }

                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <!--Data Tables jQuery-->
    <script type="text/javascript">

        $(document).ready(function () {
            var idleInterval = setInterval("reloadPage()", 300000); //5 minutos
            $('#assets-data-table').DataTable({
                paging: false,
                info: false,
                "language": {
                    "lengthMenu": "Mostrando _MENU_ registros por página",
                    "zeroRecords": "No se encontro nada con ese criterio",
                    "infoEmpty": "No hay información disponible",
                    "search": "Buscar en esta lista",
                }

            });
            $('#exportexcel').bind('click', function (e) {
                $('#assets-data-table').tableExport({ type: 'excel', escape: 'false' });
            });
        })

        function reloadPage() {
            location.reload();
        }

    </script>

}

GridExampleMVC/Views/Reporte/Productividad.cshtml
@model IEnumerable<GridExampleMVC.Models.DCM_ReportProductivity_Result>

@{
    ViewBag.Title = "Productividad";
}

<div class="row">
    <div class="col-md-12">
        <div id="list-panel">
            <div class="panel-body">
                @using (Html.BeginForm("Productividad", "Reporte", FormMethod.Post))
                {


                    @Html.Partial("_SearchbyProd")

                    <div id="dvData">
                        <table id="assets-data-table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.ACCUMULATOR)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.DATE)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.USER)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.AREA)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.CUSTOMER)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.SHIFT)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.TIMPE_LINE)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.LINE)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.ID_LINE)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.RESPROD)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.MINDESC)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.START)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.END)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.MINTRA)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.OPREG)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.HRSTRA)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.HRSGAN)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Cumplimiento)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Productividad)</th>
                                    <th class="column-title">@Html.DisplayNameFor(model => model.Eficiencia)</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.ACCUMULATOR)</td>
                                        <td>@Html.DisplayFor(modelItem => item.DATE)</td>
                                        <td>@Html.DisplayFor(modelItem => item.USER)</td>
                                        <td>@Html.DisplayFor(modelItem => item.AREA)</td>
                                        <td>@Html.DisplayFor(modelItem => item.CUSTOMER)</td>
                                        <td>@Html.DisplayFor(modelItem => item.SHIFT)</td>
                                        <td>@Html.DisplayFor(modelItem => item.TIMPE_LINE)</td>
                                        <td>@Html.DisplayFor(modelItem => item.LINE)</td>
                                        <td>@Html.DisplayFor(modelItem => item.ID_LINE)</td>
                                        <td>@Html.DisplayFor(modelItem => item.RESPROD)</td>
                                        <td>@Html.DisplayFor(modelItem => item.MINDESC)</td>
                                        <td>@Html.DisplayFor(modelItem => item.START)</td>
                                        <td>@Html.DisplayFor(modelItem => item.END)</td>
                                        <td>@Html.DisplayFor(modelItem => item.MINTRA)</td>
                                        <td>@Html.DisplayFor(modelItem => item.OPREG)</td>
                                        <td>@Html.DisplayFor(modelItem => item.HRSTRA)</td>
                                        <td>@Html.DisplayFor(modelItem => item.HRSGAN)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Cumplimiento)</td>
                                        <td>@Html.DisplayFor(model => item.Productividad)</td>
                                        <td>@Html.DisplayFor(model => item.Eficiencia)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    <div id="menu2" class="tab-pane fade">

                        <p>Some content in menu 2.</p>
                    </div>

                }
            </div>
        </div>
    </div>
</div>

@section Scripts
{

    <!--Data Tables jQuery-->

    <script type="text/javascript">
     $(document).ready(function () {
         $('#assets-data-table').DataTable({
             paging: false,
             info: false,
             "language": {
                 "lengthMenu": "Mostrando _MENU_ registros por página",
                 "zeroRecords": "No se encontro nada con ese criterio",
                 "infoEmpty": "No hay información disponible",
                 "search": "Buscar en esta lista",
             }

         });
         $('#exportexcel').bind('click', function (e) {
             $('#assets-data-table').tableExport({ type: 'excel', escape: 'false' });
         });
         $('#datetimepicker1').datetimepicker();
     });

    </script>

}

GridExampleMVC/Views/Reporte/_Searchby.cshtml
<div class="row">

    <div class="panel panel-default col-md-12">
        <div class="panel-body">
            <div class="col-md-3 col-sm-12 col-xs-12 form-group xdisplay_inputx has-feedback">
                <label class="control-label">
                    Fecha Inicial:
                </label>
                <input class="form-control has-feedback-left" id="finicial" name="finicial" placeholder="Fecha Inicial" type="text" value="">
                <span class="field-validation-valid parsley-error" data-valmsg-for="finicial" data-valmsg-replace="true"></span>
                <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                <span id="inputSuccess2Status" class="sr-only">(success)</span>
            </div>

            <div class="col-md-3 col-sm-12 col-xs-12 form-group xdisplay_inputx has-feedback">
                <label class="control-label">
                    Fecha Final:
                </label>
                <input class="form-control has-feedback-left" id="ffinal" name="ffinal" placeholder="Fecha Final" type="text" value="">
                <span class="field-validation-valid parsley-error" data-valmsg-for="ffinal" data-valmsg-replace="true"></span>
                <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                <span id="inputSuccess2Status" class="sr-only">(success)</span>

            </div>

            <div class="col-md-q">
                <label class="control-label">  </label>
                <div class="col-md-2 col-sm-12 col-xs-12 form-group">
                    <label class="control-label">
                        Shop Order:
                    </label>
                    <input class="form-control" id="sord" name="sord" placeholder="Shop Order" type="text" value="">
                </div><br>

                <span class="input-group-btn" style="padding-top: 5px";">
                    <button type="submit" class="btn btn-primary">
                        Buscar
                    </button>
                    <input type="button" value="Exportar" class="btn btn-success" id="exportexcel">
                </span>

               

            </div>

        </div>
    </div>
    <br />
    <br />
</div>

<script type="text/javascript">
    $(function () {
        $('#finicial').datetimepicker({
            format: 'YYYY-MM-DD'
        });
        $('#ffinal').datetimepicker({
            format: 'YYYY-MM-DD'
        });
    })
</script>